### ISSUE TITLE
Option to not automatically close the popover

### ISSUE THREAD

**Issue by vjcagay** [JFusco/vue-popover#1]
Thank you very much for this plugin. This is far the cleanest popover plugin for Vue yet (that I found) and it fits really well with my use cases.

Anyways, I'm trying to use this plugin to wrap some other Vue components I made (e.g. date/timepicker, search) but every time I click on those components to interact with them, the popover closes.

Can you add an option that disables closing the plugin when something is clicked inside (similar to how MacOS popovers behave)?

Edit: I created a pull request for this [#2](https://github.com/JFusco/vue-popover/pull/2). Thanks.

**Comment by JFusco** [comment]
@vjcagay Thanks for checking this out and using it, I merged your pull request. Thanks for updating the tests and keeping things clean. If you have any other ideas, please shoot them my way or create another pull request!

v1.6.0 has your pull request.

**Comment by JFusco** [comment]
v1.6.0 has your pull request!

**Comment by vjcagay** [comment]
Nice, thanks!
