### ISSUE TITLE
Wrapperless face

### ISSUE THREAD

**Issue by mikeapr4** [JFusco/vue-popover#6]
Currently this component outputs 3 extra tags around the slot templates (`div.popover`, `div.popover__face` and `div.popover__container`). I've written some code to allow this component to work without adding extra tags (using a custom render function and scoped slots).

I got the idea from portal-vue's [`slim` option](https://linusborg.github.io/portal-vue/#/guide?id=removing-the-wrapper-element).

If you are interested, I can submit a PR with the functionality I have put together. I can make it active with a `slim` option too.

**Comment by JFusco** [comment]
@mikeapr4 
Sorry for the late reply - yes, please submit a pull request and update the unit tests if needed, thanks a lot!!

**Comment by JFusco** [comment]
@mikeapr4 Can you submit your PR when you have a chance?

**Comment by mikeapr4** [comment]
Hey Joe,

Sorry, I put this aside and didn't come back to it. I'll try put some time
to it this week.

Cheers
Mike

**Comment by JFusco** [comment]
Thanks!
